WITH T1 AS (
    SELECT PMT.CREATED_DATE
         , PMT.CASE_ID
         , PMT.RECORD_TYPE
    FROM RPT.T_PAYMENT AS PMT
    WHERE TO_DATE(CREATED_DATE) = CURRENT_DATE()
      AND RECORD_TYPE != 'Permit Fees'
)

SELECT *
FROM T1