WITH CANCELLED_ACCOUNTS AS (
    SELECT P.PROJECT_NAME
         , ANY_VALUE(P.PROJECT_ID)                 AS  PROJECT_ID
         , ANY_VALUE(TO_DATE(P.INSTALLATION_COMPLETE)) INSTALLATION_DATE
         , ANY_VALUE(TO_DATE(P.CANCELLATION_DATE)) AS  CANCELLATION_DATE
         , ANY_VALUE(CAD.SYSTEM_SIZE_ACTUAL)       AS  THIS_SIZE
         , ROUND(THIS_SIZE * 1000 * 4, 2)          AS  SYSTEM_VALUE
    FROM RPT.T_PROJECT AS P
             LEFT JOIN
         RPT.T_SYSTEM_DETAILS_SNAP AS CAD
         ON CAD.PROJECT_ID = P.PROJECT_ID
    WHERE P.PROJECT_STATUS = 'Cancelled'
      AND P.INSTALLATION_COMPLETE IS NOT NULL
      AND P.CANCELLATION_DATE >= DATE_TRUNC('Y', CURRENT_DATE)
    GROUP BY P.PROJECT_NAME
)

   , VALID_ERT_CASES AS (
    SELECT C.CASE_NUMBER
         , C.PROJECT_ID
         , C.RECORD_TYPE
         , C.ORIGIN
         , C.EXECUTIVE_RESOLUTIONS_ACCEPTED AS ERA
    FROM RPT.T_CASE AS C
    WHERE ERA IS NOT NULL
      AND C.RECORD_TYPE = 'Solar - Customer Escalation'
      AND C.ORIGIN IN ('BBB', 'Legal', 'News Media')
)

   , CANCELLATION_LOR AS (
    SELECT *
    FROM CANCELLED_ACCOUNTS CA
             LEFT JOIN
         VALID_ERT_CASES AS ERT
         ON CA.PROJECT_ID = ERT.PROJECT_ID
    WHERE ERT.CASE_NUMBER IS NOT NULL
    ORDER BY PROJECT_NAME
)

SELECT *
FROM CANCELLATION_LOR