WITH PAYMENTS AS (
    SELECT P.NAME
         , PR.PROJECT_NAME
         , PR.SERVICE_NAME
         , C.CASE_NUMBER
         , P.FEE_TYPE
         , P.QUOTED_TOTAL
         , P.ACTUAL_TOTAL
         , P.PAYMENT_AMOUNT
         , TO_DATE(P.PAYMENT_DATE) AS    PAYMENT_DATE
         , CASE
               WHEN PAYMENT_DATE IS NOT NULL
                   THEN P.QUOTED_TOTAL - P.ACTUAL_TOTAL
        END                        AS    REVENUE_LOSS
         , P.CREATED_BY
         , TO_DATE(P.CREATED_DATE) AS    CREATED_DATE
         , P.LAST_MODIFIED_BY
         , TO_DATE(P.LAST_MODIFIED_DATE) LAST_MODIFIED_DATE
    FROM RPT.T_PAYMENT AS P
             LEFT JOIN
         RPT.T_PROJECT AS PR
         ON PR.PROJECT_ID = P.PROJECT_ID
             LEFT JOIN
         RPT.T_CASE AS C
         ON C.CASE_ID = P.CASE_ID
    WHERE P.RECORD_TYPE = 'Customer Payments'
      AND P.CREATED_DATE >= DATE_TRUNC('Y', CURRENT_DATE)
      AND PR.SERVICE_NAME IN
          ('{{REPLACE}}')
    ORDER BY CREATED_DATE
)

SELECT *
FROM PAYMENTS