SELECT DISTINCT AGENT_FIRST_NAME
              , AVG(QSCORE) AS SCORE
FROM D_POST_INSTALL.T_NE_AGENT_QSCORE AS QA

WHERE EVALUATION_TYPE LIKE '%RARE%'
  AND EVALUATION_TYPE LIKE '%Solutions%'
  AND EVALUATION_DATE >= DATEADD('D', -30, CURRENT_DATE())
GROUP BY AGENT_FIRST_NAME
ORDER BY SCORE DESC