WITH ALL_ER AS (
    SELECT HR.FULL_NAME
         , ANY_VALUE(HR.FIRST_NAME)                       AS FIRST_NAME
         , ANY_VALUE(HR.LAST_NAME)                        AS LAST_NAME
         , ANY_VALUE(HR.SUPERVISOR_BADGE_ID_1)            AS SUPERVISOR
         , CASE
               WHEN SUPERVISOR = 124126 THEN 'Tier I'
               WHEN SUPERVISOR = 208513 THEN 'Tier II'
               WHEN SUPERVISOR = 67600 THEN 'Default' END AS AGENT_TIER
         , ANY_VALUE(HR.SUPERVISOR_NAME_1)                AS SUP_NAME
         , MIN(HR.CREATED_DATE)                           AS TEAM_START_DATE
         , MAX(HR.EXPIRY_DATE)                            AS TEAM_END_DATE
         , ANY_VALUE(HR.TERMINATED)                       AS TERMINATED
         , ANY_VALUE(HR.SF_REP_ID)                        AS SF_ID
    FROM HR.T_EMPLOYEE_ALL AS HR
    WHERE HR.SUPERVISOR_BADGE_ID_2 = 101769
    GROUP BY HR.FULL_NAME
    ORDER BY TEAM_START_DATE DESC
)

   , AGENTS_QA AS (
    /*
     AGENT_DISPLAY_ID
     EVALUATION
     CALL_DATE
     */

    SELECT QA.AGENT_DISPLAY_ID
         , ANY_VALUE(QA.EVALUATION_TOTAL_SCORE) AS QA_SCORE
         , ANY_VALUE(ER.AGENT_TIER)             AS AGENT_TIER
         , ANY_VALUE(QA.START_TIME)             AS CALL_START
    FROM CALABRIO.T_RECORDING_CONTACT AS QA
             LEFT JOIN ALL_ER AS ER
                       ON QA.AGENT_DISPLAY_ID = ER.FULL_NAME
    WHERE QA.START_TIME BETWEEN
        DATE_TRUNC('MM', DATEADD('MM', -1, CURRENT_DATE)) AND
        LAST_DAY(DATEADD('MM', -1, CURRENT_DATE))
      AND ER.AGENT_TIER IS NOT NULL
    GROUP BY QA.AGENT_DISPLAY_ID
)

   , QA_TABLE AS (
    SELECT QA.AGENT_DISPLAY_ID      AS AGENT_NAME
         , ANY_VALUE(QA.AGENT_TIER) AS AGENT_TIER
         , AVG(QA.QA_SCORE)         AS AVG_QA
    FROM AGENTS_QA AS QA
    GROUP BY AGENT_NAME
    ORDER BY AGENT_TIER, AVG_QA DESC
)

SELECT *
FROM QA_TABLE