CREATE OR REPLACE VIEW D_POST_INSTALL.V_FILINGS_BATCH_TIMEFRAME_DETAILS AS
(
-- Create the view
SELECT D.DT
     , D.WEEK_DAY_NUM
     , D.DAY_NAME
     , D.DAY_NAME_ABR
     , ROW_NUMBER() OVER (ORDER BY D.DT) AS BATCH_NUMBER
     , DATEADD('D', -7, D.DT)            AS BATCH_START
     , DATEADD('D', -1, D.DT)            AS BATCH_END
     , BATCH_START || ' - ' || BATCH_END AS TIMEFRAME
FROM RPT.T_DATES AS D
WHERE D.DT BETWEEN
    '2013-11-07' AND
    CURRENT_DATE
  AND D.DAY_NAME_ABR = 'WED'
ORDER BY D.DT DESC
);

GRANT SELECT ON VIEW D_POST_INSTALL.V_FILINGS_BATCH_TIMEFRAME_DETAILS TO GENERAL_REPORTING_R -- Share the view