CREATE TABLE VSLR.D_POST_INSTALL.T_LD_BATCH_ACCOUNT_LISTS
(
    BATCH_TYPE             VARCHAR,
    CONTRACT_TYPE          VARCHAR,
    CUSTOMER_1_FIRST       VARCHAR,
    CUSTOMER_1_LAST        VARCHAR,
    CUSTOMER_1_MIDDLE      VARCHAR,
    CUSTOMER_1_SUFFIX      VARCHAR,
    CUSTOMER_2_FIRST       VARCHAR,
    CUSTOMER_2_LAST_NAME   VARCHAR,
    CUSTOMER_2_MIDDLE      VARCHAR,
    CUSTOMER_2_SUFFIX_NAME VARCHAR,
    INSTALL_DATE           DATE,
    PROJECT_NAME           VARCHAR,
    SERVICE_ADDRESS        VARCHAR,
    SERVICE_CITY           VARCHAR,
    SERVICE_COUNTY         VARCHAR,
    SERVICE_NAME           VARCHAR,
    SERVICE_STATE          VARCHAR,
    SERVICE_ZIP_CODE       VARCHAR,
    TERMINATION_DATE       DATE,
    TRANSACTION_DATE       DATE,
    WEEK_BATCH             INT
)