/*
 STEP 1
 */
BEGIN;


/*
 STEP 2
 */
CREATE OR REPLACE TABLE VSLR.D_POST_INSTALL.T_CX_ROOT_CAUSE_TAGS
(
    SUBMITTED_TIMESTAMP TIMESTAMP,
    SUBMITTED_EMAIL     VARCHAR,
    CASE_CREATED_DATE   DATE,
    CASE_NUMBER         VARCHAR,
    SERVICE_NUMBER      VARCHAR,
    SERVICE_STATE       VARCHAR,
    OWNER               VARCHAR,
    ORIGIN              VARCHAR,
    PRIORITY_BUCKET     VARCHAR,
    ROOT_CAUSE_TAG      VARCHAR,
    CASE_TEAM           VARCHAR
);

SELECT *
    FROM D_POST_INSTALL.T_CX_ROOT_CAUSE_TAGS
        ;

/*
 STEP 3
 */
COMMIT; -- OPT A
ROLLBACK; -- OPT B