/*
 STEP 1
 */
BEGIN;


/*
 STEP 2
 */
DROP TABLE D_POST_INSTALL.T_PTO_TO_BILLING_TMP_EMAIL_OPENS
;

CREATE TABLE D_POST_INSTALL.T_ERT_CLOSED_WON_CASES
(
    SERVICE_NAME   VARCHAR,
    CASE_NUMBER    VARCHAR,
    CASE_SUBJECT   VARCHAR,
    CASE_AGE       FLOAT,
    CASE_CLOSED_BY VARCHAR,
    CLOSED_WON     VARCHAR,
    PRIMARY_REASON VARCHAR,
    REASON         VARCHAR
)
    comment = 'This table is intended to be a temporary solution to track which of ERTs cases are "Closed Won".';
;

SELECT *
FROM D_POST_INSTALL.T_ERT_CLOSED_WON_CASES
;

/*
 STEP 3
 */
COMMIT; -- OPT A
ROLLBACK; -- OPT B