WITH ACTIVE_CASE_LIST AS (
    SELECT C.CASE_NUMBER
         , C.OWNER
         , C.ORIGIN
         , C.EXECUTIVE_RESOLUTIONS_ACCEPTED AS ERA
         , C.CLOSED_DATE
         , P.SERVICE_NAME
         , P.SOLAR_BILLING_ACCOUNT_NUMBER
         , P.PROJECT_NAME
    FROM RPT.T_CASE AS C
             LEFT JOIN RPT.T_PROJECT AS P
                       ON P.PROJECT_ID = C.PROJECT_ID
    WHERE C.RECORD_TYPE = 'Solar - Customer Escalation'
      AND C.EXECUTIVE_RESOLUTIONS_ACCEPTED IS NOT NULL
)

SELECT DISTINCT SERVICE_NAME
              , SOLAR_BILLING_ACCOUNT_NUMBER
              , CASE
                    WHEN TO_DATE(ERA) = DATEADD('D', -1, CURRENT_DATE)
                        THEN 'CORP'
                    WHEN TO_DATE(CLOSED_DATE) = DATEADD('D', -1, CURRENT_DATE)
                        THEN 'NONE'
    END AS CODE_AS
FROM ACTIVE_CASE_LIST
WHERE TO_DATE(ERA) = DATEADD('D', -1, CURRENT_DATE)
   OR TO_DATE(CLOSED_DATE) = DATEADD('D', -1, CURRENT_DATE)
ORDER BY CODE_AS