WITH REPORT AS (
    SELECT TO_DATE(ANY_VALUE(P.PTO_AWARDED)) AS PTO_AWARDED
         , ANY_VALUE(O.CONTRACT_SIGNER)      AS CONTRACT_SIGNER
         , ANY_VALUE(C.FIRST_NAME)           AS FIRST_NAME
         , ANY_VALUE(C.LAST_NAME)            AS LAST_NAME
         , ANY_VALUE(C.EMAIL)                AS EMAIL
         , ANY_VALUE(E."Subscriber Key")     AS SUBSCRIBER_KEY
         , P.SERVICE_NUMBER
         , CURRENT_DATE                      AS LAST_REFRESHED
    FROM RPT.T_PROJECT AS P
             LEFT OUTER JOIN RPT.T_OPPORTUNITY AS O
                             ON O.ACCOUNT_ID = P.ACCOUNT_ID
             LEFT OUTER JOIN RPT.T_CONTACT AS C
                             ON C.ACCOUNT_ID = P.ACCOUNT_ID
             LEFT OUTER JOIN D_POST_INSTALL.T_PTO_TO_BILLING_EMAILS AS E
                             ON E."Service Number" = P.SERVICE_NUMBER
    WHERE P.PTO_AWARDED IS NOT NULL
      AND PTO_AWARDED BETWEEN
        DATE_TRUNC('Y', CURRENT_DATE) AND
        LAST_DAY(DATE_TRUNC('MM', DATEADD('MM', -1, CURRENT_DATE)))
      AND O.CONTRACT_SIGNER IS NOT NULL
      AND C.EMAIL IS NOT NULL
      AND C.FIRST_NAME IS NOT NULL
      AND P.SERVICE_NUMBER IS NOT NULL
    GROUP BY P.SERVICE_NUMBER
)

   , TREND AS (
    SELECT DATE_TRUNC('MM', D.DT)                                    AS MONTH
         , COUNT(CASE WHEN TO_DATE(R.PTO_AWARDED) = D.DT THEN 1 END) AS CT
    FROM RPT.T_DATES AS D
             INNER JOIN REPORT AS R
                        ON TO_DATE(R.PTO_AWARDED) = D.DT
    GROUP BY MONTH
    ORDER BY MONTH DESC
)

   , EMAILS AS (
    SELECT DISTINCT E."Service Number"
    FROM D_POST_INSTALL.T_PTO_TO_BILLING_EMAILS AS E
)

SELECT *
FROM EMAILS