WITH CASES AS (
    SELECT C.CASE_NUMBER
         , C.PROJECT_ID
         , TO_DATE(C.CREATED_DATE)      AS CREATED_DATE
         , TO_DATE(STATUS_LAST_UPDATED) AS STATUS_LAST_UPDATE
         , C.STATUS
         , C.PRIMARY_REASON
         , C.CASE_ID
    FROM RPT.T_CASE AS C
    WHERE C.RECORD_TYPE ILIKE '%TRANSFER%'
      AND C.PRIMARY_REASON ILIKE '%REFINANCE%'
      AND C.CREATED_DATE >= DATE_TRUNC('Y', CURRENT_DATE)
)

   , CASE_HISTORY AS (
    SELECT C.CASE_NUMBER
         , C.CREATED_DATE
         , C.PROJECT_ID
         , C.STATUS_LAST_UPDATE
         , E.FULL_NAME                                                    AS CHANGE_MADE_BY
         , CH.FIELD
         , TO_DATE(CH.CREATEDDATE)                                        AS CHANGE_DATE
         , LEAD(TO_DATE(CH.CREATEDDATE))
                OVER (PARTITION BY C.CASE_NUMBER ORDER BY CH.CREATEDDATE) AS NEXT_CHANGE_DATE
         , DATEDIFF(dd, CHANGE_DATE, NVL(NEXT_CHANGE_DATE, CURRENT_DATE)) AS GAP
         , DATEADD(dd, 60, CHANGE_DATE)                                   AS ESTIMATED_BATCH_DATE
         , DATEADD(dd, DATEDIFF(dd,
                                CHANGE_DATE,
                                NVL(NEXT_CHANGE_DATE,
                                    ESTIMATED_BATCH_DATE)),
                   CHANGE_DATE)                                           AS QUEUE_REMOVAL_DATE
         , CH.NEWVALUE
         , LEAD(CH.NEWVALUE)
                OVER (PARTITION BY C.CASE_NUMBER ORDER BY CH.CREATEDDATE) AS NEXT_VALUE
    FROM CASES AS C
             LEFT OUTER JOIN RPT.V_SF_CASEHISTORY AS CH
                             ON CH.CASEID = C.CASE_ID
             LEFT OUTER JOIN D_POST_INSTALL.T_EMPLOYEE_MASTER AS E
                             ON E.SALESFORCE_ID = CH.CREATEDBYID
    WHERE FIELD ILIKE '%STATUS%'
    ORDER BY C.CASE_NUMBER DESC
           , CH.CREATEDDATE
)

   , MAIN AS (
    SELECT *
    FROM CASE_HISTORY
    WHERE NEWVALUE ILIKE '%READY%'
)

   , TEST_RESULTS AS (
    SELECT COUNT(PROJECT_ID)
         , COUNT(DISTINCT PROJECT_ID)
    FROM MAIN
)

SELECT *
FROM MAIN
