WITH T1 AS (
    SELECT P.PROJECT_ID
         , ANY_VALUE(P.PROJECT_NAME)                       AS PROJECT_NAME
         , ANY_VALUE(P.PROJECT_NUMBER)                     AS PROJECT_NUMBER
         , ANY_VALUE(P.PROJECT_CREATED_DATE)               AS PROJECT_CREATED_DATE
         , ANY_VALUE(P.CANCELLATION_DATE)                  AS CANCELLATION_DATE
         , ANY_VALUE(P.CANCELLED_FLAG)                     AS CANCELLED_FLAG
         , ANY_VALUE(CAD.SYSTEM_SIZE)                      AS SYSTEM_SIZ
         , ROUND(ANY_VALUE(CAD.SYSTEM_SIZE) * 1000 * 7, 2) AS SYSTEM_VALUE
         , LD.COLLECTION_CODE
    FROM RPT.T_PROJECT AS P

             LEFT OUTER JOIN
         RPT.T_SYSTEM_DETAILS_SNAP AS CAD
         ON CAD.PROJECT_ID = P.PROJECT_ID

             LEFT OUTER JOIN
         LD.T_DAILY_DATA_EXTRACT_HIST AS LD
         ON LD.BILLING_ACCOUNT = P.SOLAR_BILLING_ACCOUNT_NUMBER

    WHERE P.PROJECT_STATUS = 'Cancelled'
      AND P.INSTALLATION_COMPLETE IS NOT NULL
      AND LD.COLLECTION_CODE IN ('BK07', 'BK13', 'DCNT', 'FORE')
      AND P.CANCELLATION_DATE BETWEEN DATEADD('MM', -3, DATE_TRUNC('MM', CURRENT_DATE()))
        AND DATEADD('MM', -0, DATE_TRUNC('MM', CURRENT_DATE()))
    GROUP BY P.PROJECT_ID, LD.COLLECTION_CODE
    ORDER BY P.PROJECT_ID
)

SELECT *
FROM T1