WITH ERT_CASES AS (
    SELECT C.PROJECT_ID
         , C.CASE_ID
         , C.CASE_NUMBER
         , C.ORIGIN
         , C.RECORD_TYPE
         , C.OWNER
         , C.SOLAR_QUEUE
         , C.SUBJECT
         , C.CREATED_DATE
         , C.CLOSED_DATE
         , C.STATUS
         , IFF(C.ORIGIN IN ('BBB', 'News Media', 'Legal', 'Executive'), 'Tier II', 'Tier I') AS TEAM
    FROM RPT.T_CASE AS C
    WHERE C.RECORD_TYPE = 'Solar - Customer Escalation'
      AND C.EXECUTIVE_RESOLUTIONS_ACCEPTED IS NOT NULL
      AND C.SUBJECT NOT ILIKE '%VIP%'
      AND C.SUBJECT NOT ILIKE '%NPS%'
      AND C.SUBJECT NOT ILIKE '%COMP%'
      AND C.SUBJECT NOT ILIKE '%POSITIVE%'
      AND C.CLOSED_DATE IS NOT NULL
--       AND C.CREATED_DATE >= DATE_TRUNC('Y', CURRENT_DATE)
)

   , CASE_COMMENTS AS (
    SELECT EC.*
         , CC.CREATEDBYID
         , CC.CREATEDATE
         , COUNT(CASE_ID) OVER (PARTITION BY CASE_ID) AS COMMENTS
    FROM ERT_CASES AS EC
             LEFT OUTER JOIN RPT.V_SF_CASECOMMENT AS CC
                             ON CC.PARENTID = EC.CASE_ID
)

   , CASE_UPDATES AS (
    SELECT CC.CASE_ID
         , ANY_VALUE(CC.PROJECT_ID)   AS PROJECT_ID
         , ANY_VALUE(CC.CASE_NUMBER)  AS CASE_NUMBER
         , ANY_VALUE(CC.ORIGIN)       AS ORIGIN
         , ANY_VALUE(CC.RECORD_TYPE)  AS RECORD_TYPE
         , ANY_VALUE(CC.OWNER)        AS OWNER
         , ANY_VALUE(CC.SOLAR_QUEUE)  AS SOLAR_QUEUE
         , ANY_VALUE(CC.SUBJECT)      AS SUBJECT
         , ANY_VALUE(CC.CREATED_DATE) AS CREATED_DATE
         , ANY_VALUE(CC.CLOSED_DATE)  AS CLOSED_DATE
         , ANY_VALUE(CC.STATUS)       AS STATUS
         , ANY_VALUE(CC.TEAM)         AS TEAM
         , ANY_VALUE(CC.CREATEDBYID)  AS CREATEDBYID
         , ANY_VALUE(CC.CREATEDATE)   AS CREATEDATE
         , ANY_VALUE(CC.COMMENTS)     AS COMMENTS
    FROM CASE_COMMENTS AS CC
    GROUP BY CC.CASE_ID
    ORDER BY CC.CASE_ID DESC
)

   , TEAM_METRICS AS (
    SELECT TEAM
         , AVG(COMMENTS)   AS AVG_TOUCHES
         , COUNT(COMMENTS) AS VOLUME
    FROM CASE_UPDATES
    GROUP BY TEAM
    ORDER BY TEAM
)

SELECT *
FROM TEAM_METRICS
;