WITH AGENT_TABLE AS (
    SELECT DE.FULL_NAME
         , DE.EMPLOYEE_ID
         , DE.EFFECTIVENESS
         , DE.EFFICIENCY
         , DE.QUALITY
    FROM D_POST_INSTALL.V_CX_KPIS_DEFAULT AS DE
)

SELECT *
FROM AGENT_TABLE
