WITH RANKING_TABLE AS (
    SELECT ER.FULL_NAME
         , ER.EMPLOYEE_ID
         , ER.EFFECTIVENESS
         , ER.EFFICIENCY
         , ER.QUALITY
         , POW(PERCENT_RANK() OVER (ORDER BY NVL(ER.EFFECTIVENESS, 0) ASC), 1) AS EFFECTIVENESS_RANK
         , POW(PERCENT_RANK() OVER (ORDER BY ER.EFFICIENCY DESC), 1)           AS EFFICIENCY_RANK
         , POW(PERCENT_RANK() OVER (ORDER BY NVL(ER.QUALITY, 0) ASC), 1)       AS QUALITY_RANK
         , (EFFECTIVENESS_RANK + EFFICIENCY_RANK + QUALITY_RANK) / 3           AS WEIGHTED_RANK
    FROM D_POST_INSTALL.V_CX_KPIS_ER_T1 AS ER
)

   , MAIN AS (
    SELECT *
    FROM RANKING_TABLE
    ORDER BY WEIGHTED_RANK DESC
    LIMIT 5
)

   , TEST_CTE AS (
    SELECT *
    FROM RANKING_TABLE
)

SELECT *
FROM MAIN
