WITH AGENT_TABLE AS (
    SELECT ER.FULL_NAME
         , ER.EMPLOYEE_ID
         , ER.EFFECTIVENESS
         , ER.EFFICIENCY
         , ER.QUALITY
    FROM D_POST_INSTALL.V_CX_KPIS_ER_T2 AS ER
)

SELECT *
FROM AGENT_TABLE