WITH RANKING_TABLE AS (
    SELECT RM.FULL_NAME
         , RM.EMPLOYEE_ID
         , RM.EFFECTIVENESS
         , RM.EFFICIENCY
         , RM.QUALITY
         , POW(PERCENT_RANK() OVER (ORDER BY NVL(RM.EFFECTIVENESS, 0)), 1) AS EFFECTIVENESS_RANK
         , rank() OVER (ORDER BY NVL(RM.EFFECTIVENESS, 0) DESC)            AS EFFECTIVENESS_INT_RANK
         , POW(PERCENT_RANK() OVER (ORDER BY RM.EFFICIENCY DESC), 1)       AS EFFICIENCY_RANK
         -- POW(PERCENT_RANK() OVER (ORDER BY RM.EFFICIENCY DESC), 1)
         , rank() OVER (ORDER BY RM.EFFICIENCY)                            AS EFFICIENCY_INT_RANK
         -- rank() OVER (ORDER BY RM.EFFICIENCY)
         , POW(PERCENT_RANK() OVER (ORDER BY NVL(RM.QUALITY, 0)), 1)       AS QUALITY_RANK
         , rank() OVER (ORDER BY NVL(RM.QUALITY, 0) DESC)                  AS QUALITY_INT_RANK
         , (EFFECTIVENESS_RANK + QUALITY_RANK) / 2                         AS WEIGHTED_RANK
    FROM D_POST_INSTALL.V_CX_KPIS_DEFAULT_RISK_MITIGATION AS RM
)

   , MAIN AS (
    SELECT *
    FROM RANKING_TABLE
    ORDER BY WEIGHTED_RANK DESC
    LIMIT 5
)

   , TEST_CTE AS (
    SELECT *
    FROM RANKING_TABLE
)

SELECT *
FROM MAIN
