SELECT SYS.PROJECT_ID
     , SYS.PRODUCTION_PERIOD
, SYS.AS_BUILT_SYSTEM_SIZE
, SYS.AS_BUILT_PRODUCTION_ANNUAL
, SYS.DAYS_PASSED_INSTALL
, SYS.MONTHLY_DEGRADED_PRODUCTION_KWH
, SYS.MONTHLY_NOMINAL_VALUE_SCHEDULE
FROM RPT.T_NV_PV_DSAB_CALCULATIONS AS SYS
WHERE SYS.PROJECT_NAME = 'SP-3368211'
ORDER BY SYS.PRODUCTION_PERIOD