SELECT P.PROJECT_NAME
     , P.SERVICE_NUMBER
     , P.INSTALLATION_COMPLETE
     , P.PTO_AWARDED
     , D.DT
     , P.START_BILLING
     , CT.EMAIL
     , CT.FULL_NAME
     , P.SERVICE_STATE
     , CURRENT_DATE AS LAST_REFRESHED
FROM RPT.T_DATES AS D
         INNER JOIN RPT.T_PROJECT AS P
                    ON TO_DATE(P.PTO_AWARDED) = D.DT
         LEFT OUTER JOIN RPT.T_CONTACT AS CT
                         ON CT.ACCOUNT_ID = P.ACCOUNT_ID
WHERE PTO_AWARDED IS NOT NULL
  AND D.DT BETWEEN
    DATE_TRUNC('Y', CURRENT_DATE) AND
    CURRENT_DATE