WITH ALL_INSTALLS AS (
    SELECT P.PROJECT_NAME
         , P.INSTALLATION_COMPLETE
    FROM RPT.T_PROJECT AS P
    WHERE P.INSTALLATION_COMPLETE IS NOT NULL
)

   , TIMEFRAME_CALCULATION AS (
    SELECT D.DT
         , D.WEEK_DAY_NUM
         , COUNT(CASE WHEN TO_DATE(ALL_INSTALLS.INSTALLATION_COMPLETE) = D.DT THEN 1 END) AS DAILY_INSTALLS
         , DATEADD('D', -6, D.DT) || ' - ' || D.DT                                        AS TIMEFRAME
         , SUM(DAILY_INSTALLS) OVER(ORDER BY DT ASC
               ROWS BETWEEN 6 PRECEDING AND CURRENT ROW)                                  AS INSTALLS_DURING_TIMEFRAME
    FROM ALL_INSTALLS,
         RPT.T_DATES AS D
    WHERE D.DT BETWEEN DATEADD('Y', -1, CURRENT_DATE()) AND CURRENT_DATE()
    GROUP BY D.DT
           , D.WEEK_DAY_NUM
    ORDER BY D.DT
)

SELECT TIMEFRAME
     , INSTALLS_DURING_TIMEFRAME
FROM TIMEFRAME_CALCULATION
WHERE WEEK_DAY_NUM = 4
  AND DT >= DATE_TRUNC('Y', CURRENT_DATE())

