WITH ALL_INSTALLS AS (
    SELECT P.PROJECT_NAME
         , P.INSTALLATION_COMPLETE
         , P.SERVICE_STATE
    FROM RPT.T_PROJECT AS P
    WHERE P.INSTALLATION_COMPLETE IS NOT NULL
)

   , TIMEFRAME_CALCULATION AS (
    SELECT D.DT
         , D.WEEK_DAY_NUM
         , COUNT(CASE
                     WHEN TO_DATE(ALL_INSTALLS.INSTALLATION_COMPLETE) = D.DT
                         THEN 1 END)                     AS DAILY_INSTALLS
         , COUNT(CASE
                     WHEN TO_DATE(ALL_INSTALLS.INSTALLATION_COMPLETE) = D.DT
                         AND ALL_INSTALLS.SERVICE_STATE = 'CA'
                         THEN 1 END)                     AS PUC_INSTALLS
         , COUNT(CASE
                     WHEN TO_DATE(ALL_INSTALLS.INSTALLATION_COMPLETE) = D.DT
                         AND ALL_INSTALLS.SERVICE_STATE != 'CA'
                         THEN 1 END)                     AS UCC_INSTALLS
         , DATEADD('D', -6, D.DT) || ' - ' || D.DT       AS TIMEFRAME
         , SUM(DAILY_INSTALLS) OVER(ORDER BY DT ASC
               ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS INSTALLS_DURING_TIMEFRAME
         , SUM(PUC_INSTALLS) OVER(ORDER BY DT ASC
               ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS PUC_INSTALLS_DURING_TIMEFRAME
         , SUM(UCC_INSTALLS) OVER(ORDER BY DT ASC
               ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS UCC_INSTALLS_DURING_TIMEFRAME
    FROM ALL_INSTALLS,
         RPT.T_DATES AS D
    WHERE D.DT BETWEEN DATEADD('Y', -1, CURRENT_DATE()) AND CURRENT_DATE()
    GROUP BY D.DT
           , D.WEEK_DAY_NUM
    ORDER BY D.DT
)

   , FINAL AS (
    SELECT TIMEFRAME
         , INSTALLS_DURING_TIMEFRAME
         , PUC_INSTALLS_DURING_TIMEFRAME
         , UCC_INSTALLS_DURING_TIMEFRAME
    FROM TIMEFRAME_CALCULATION
    WHERE WEEK_DAY_NUM = 4
      AND DT >= DATE_TRUNC('Y', CURRENT_DATE())
)

SELECT *
FROM FINAL
