WITH T1 AS (
    SELECT P.PROJECT_NUMBER
         , ANY_VALUE(CAD.SYSTEM_SIZE_ACTUAL_KW)      AS SYSTEM_SIZE
         , ANY_VALUE(CAD.DESIGNED_OFFSET_PERCENTAGE) AS OFFSET_PERCENT
         , ANY_VALUE(C.TRANSACTION_DATE)             AS INSTALLATION_COMPLETE
    FROM RPT.T_PROJECT AS P
             LEFT OUTER JOIN
         RPT.T_CAD AS CAD
         ON CAD.PROJECT_ID = P.PROJECT_ID
             INNER JOIN
         RPT.T_CONTRACT AS C
         ON P.PRIMARY_CONTRACT_ID = C.CONTRACT_ID
    WHERE C.TRANSACTION_DATE < CURRENT_DATE()
      AND P.INSTALLATION_COMPLETE IS NOT NULL
      AND P.SERVICE_STATE = 'FL'
      AND CAD.IS_PRIMARY_CAD = 'Y'
      AND CAD.DESIGNED_OFFSET_PERCENTAGE < 85
      AND CAD.DESIGNED_OFFSET_PERCENTAGE >= 40
--       AND SYSTEM_SIZE_ACTUAL_KW >= 11
--       AND SYSTEM_SIZE_ACTUAL_KW < 12
    GROUP BY P.PROJECT_NUMBER
    ORDER BY P.PROJECT_NUMBER
)

SELECT COUNT(PROJECT_NUMBER) AS TOTAL
FROM T1