SELECT count(p.PROJECT_ID) AS "Systems"
FROM RPT.T_PROJECT AS P
         INNER JOIN
     RPT.T_SERVICE AS S
     ON P.PROJECT_ID = S.PROJECT_ID
WHERE P.INSTALLATION_COMPLETE IS NOT NULL
  AND S.SERVICE_STATUS NOT LIKE '%Cancelled%'