WITH CASE_LIST AS (
    SELECT C.CASE_NUMBER
         , P.SERVICE_STATE
         , C.CREATED_DATE
         , C.CLOSED_DATE
    , C.EXECUTIVE_RESOLUTIONS_ACCEPTED AS ERA
    FROM RPT.T_CASE AS C
             LEFT JOIN
         RPT.T_PROJECT AS P
         ON P.PROJECT_ID = C.PROJECT_ID
    WHERE P.SERVICE_STATE = 'NJ'
      AND C.CLOSED_DATE IS NULL
      AND C.RECORD_TYPE = 'Solar - Customer Escalation'
)

SELECT count(CASE WHEN ERA IS NOT NULL THEN 1 END) AS ERA_COUNT
, COUNT(CASE WHEN ERA IS NULL THEN 1 END) AS NOT_ERA_COUNT
FROM CASE_LIST