WITH T1 AS (
    SELECT COUNT(p.PROJECT_ID)
    FROM RPT.T_PROJECT AS P
    WHERE P.INSTALLATION_COMPLETE IS NOT NULL
      AND P.SERVICE_STATE = 'PA'
      AND P.PROJECT_STATUS NOT LIKE '%Canc%'
)

SELECT *
FROM T1