WITH T1 AS (
    SELECT DISTINCT P.PROJECT_NAME
                  , C.CASE_NUMBER
                  , C.EXECUTIVE_RESOLUTIONS_ACCEPTED
    FROM RPT.T_PROJECT AS P
             LEFT OUTER JOIN
         RPT.T_CASE AS C
         ON C.PROJECT_ID = P.PROJECT_ID
    WHERE P.INSTALLATION_COMPLETE IS NOT NULL
      AND P.SERVICE_STATE = 'PA'
      AND P.PROJECT_STATUS NOT LIKE '%Canc%'
      AND C.RECORD_TYPE = 'Solar - Customer Escalation'
      AND C.EXECUTIVE_RESOLUTIONS_ACCEPTED IS NOT NULL
)

SELECT COUNT(*)
FROM T1