WITH BBB_CASES AS (
    SELECT C.CASE_NUMBER
         , C.CREATED_DATE
         , C.EXECUTIVE_RESOLUTIONS_ACCEPTED AS ERA
         , P.SERVICE_STATE
    FROM RPT.T_CASE AS C
             LEFT JOIN
         RPT.T_PROJECT AS P
         ON P.PROJECT_ID = C.PROJECT_ID
    WHERE C.RECORD_TYPE = 'Solar - Customer Escalation'
      AND C.ORIGIN = 'BBB'
      AND C.CREATED_DATE >= DATE_TRUNC('Y', DATEADD('Y', -1, CURRENT_DATE))
)

   , CORE_TABLE AS (
    SELECT DATE_TRUNC('MM', D.DT)                                       AS MONTH1
         , BBB.SERVICE_STATE
         , COUNT(CASE WHEN TO_DATE(BBB.CREATED_DATE) = D.DT THEN 1 END) AS BBB_INFLOW
    FROM RPT.T_DATES AS D,
         BBB_CASES AS BBB
    WHERE D.DT BETWEEN
              DATE_TRUNC('Y', DATEADD('Y', -1, CURRENT_DATE)) AND
              LAST_DAY(DATEADD('MM', -1, CURRENT_DATE))
       GROUP BY MONTH1, BBB.SERVICE_STATE
       ORDER BY MONTH1, BBB.SERVICE_STATE
)

SELECT *
FROM CORE_TABLE