SELECT C.RECORD_TYPE
     , C.NEW_FIELD_VALUE
     , C.OWNER
     , ORIGIN
     , C.CASE_NUMBER
     , AVG(LAG_FIELD_GAP) / (60 * 60 * 24) AS GAP_DAYS
FROM D_POST_INSTALL.V_CX_CASE_CUBE AS C
WHERE C.RECORD_TYPE = 'Solar - Customer Escalation'
  AND C.FIELD_CHANGED = 'Status'
  AND C.ORIGIN ILIKE '%PHONE%'
  AND C.EXECUTIVE_RESOLUTIONS_ACCEPTED IS NOT NULL
GROUP BY C.RECORD_TYPE, C.NEW_FIELD_VALUE, C.OWNER, ORIGIN, C.CASE_NUMBER
ORDER BY AVG(LAG_FIELD_GAP) DESC