WITH PROJECTS_RAW AS (
    SELECT PROJECT_ID
         , NVL(SERVICE_STATE, '[blank]')  AS STATE_NAME
         , TO_DATE(INSTALLATION_COMPLETE) AS INSTALL_DATE
         , TO_DATE(CANCELLATION_DATE)     AS CANCELLATION_DATE
    FROM RPT.T_PROJECT
    WHERE INSTALLATION_COMPLETE IS NOT NULL
)

   , I_DAY_WIP AS (
    SELECT D.DT
         , STATE_NAME
         , COUNT(CASE
                     WHEN PR.INSTALL_DATE <= D.DT AND
                          (PR.CANCELLATION_DATE >= D.DT OR
                           PR.CANCELLATION_DATE IS NULL)
                         THEN 1 END) AS ACTIVE_INSTALLS
    FROM PROJECTS_RAW AS PR
       , RPT.T_DATES AS D
    WHERE D.DT BETWEEN
              DATE_TRUNC('Y', DATEADD('Y', -1, CURRENT_DATE)) AND
              CURRENT_DATE
    GROUP BY D.DT
           , STATE_NAME
    ORDER BY STATE_NAME
           , D.DT
)

   , I_MONTH_WIP AS (
    SELECT IW.DT       AS MONTH
         , YEAR(MONTH) AS YEAR
         , IW.STATE_NAME
         , IW.ACTIVE_INSTALLS
    FROM I_DAY_WIP IW
    WHERE DT = LAST_DAY(DT)
       OR DT = CURRENT_DATE()
    ORDER BY STATE_NAME, DT
)

SELECT *
FROM I_MONTH_WIP
;