SELECT LAST_DAY(D.DT) AS MONTH
     , YEAR(MONTH)    AS YEAR
FROM RPT.T_DATES AS D
WHERE D.DT BETWEEN
    DATE_TRUNC('Y', DATEADD('Y', -1, CURRENT_DATE)) AND
    CURRENT_DATE
  AND D.DT = LAST_DAY(D.DT)