SELECT D.DT        AS MONTH
     , YEAR(MONTH) AS YEAR
FROM RPT.T_DATES AS D
WHERE D.DT BETWEEN
    DATE_TRUNC('Y', DATEADD('Y', -1, CURRENT_DATE)) AND
    CURRENT_DATE
  AND DAY(D.DT) = DAY(CURRENT_DATE)