/*
 Needed Fields:
 DT
 ORG_BUCKET
 SERVICE_STATE
 */
WITH NPS_VIEW AS (
    SELECT NPS.SURVEY_TYPE
         , TO_DATE(NPS.SURVEY_ENDED_AT)  AS SURVEY_COMPLETED_DATE
         , NPS.PROJECT_ID
         , NPS.NPS_SCORE
         , P.SERVICE_STATE
         , 1                             AS SURVEY_TALLY
         , IFF(NPS.NPS_SCORE >= 9, 1, 0) AS PROMOTER_TALLY
         , IFF(NPS.NPS_SCORE <= 6, 1, 0) AS DETRACTOR_TALLY
    FROM D_POST_INSTALL.T_NPS_SURVEY_RESPONSE AS NPS
             LEFT OUTER JOIN RPT.T_PROJECT AS P
                             ON P.PROJECT_ID = NPS.PROJECT_ID
    WHERE NPS.SURVEY_TYPE ILIKE '%600%'
      AND NPS.NPS_SCORE IS NOT NULL
)

   , MAIN AS (
    SELECT *
    FROM NPS_VIEW
)

SELECT *
FROM MAIN