WITH AGENT_TABLE AS (
    SELECT DE.FULL_NAME
         , DE.EMPLOYEE_ID
         , DE.EFFECTIVENESS
         , TO_CHAR(DE.EFFICIENCY, '999.0') AS EFFICIENCY
         , TO_CHAR(DE.QUALITY, '999.0') || '%' AS QUALITY
    FROM D_POST_INSTALL.V_CX_KPIS_DEFAULT AS DE
)

SELECT *
FROM AGENT_TABLE