WITH AGENT_TABLE AS (
    SELECT DD.FULL_NAME
         , DD.EMPLOYEE_ID
         , DD.EFFECTIVENESS
         , TO_CHAR(DD.EFFICIENCY, '999.0') AS EFFICIENCY
         , TO_CHAR(DD.QUALITY, '999.0') || '%' AS QUALITY
    FROM D_POST_INSTALL.V_CX_KPIS_DEFAULT_DECEASED AS DD
)

SELECT *
FROM AGENT_TABLE
