WITH AGENT_TABLE AS (
    SELECT DD.OWNER
    , DD.OWNER_EMPLOYEE_ID
    , DD.CLOSED AS CLOSED_WON
    , DD.AVG_WIP_CYCLE AS CASE_AGE
    , DD.AVG_QA_SCORE AS QA
    FROM D_POST_INSTALL.V_CX_DEFAULT_DECEASED AS DD
)

SELECT *
FROM AGENT_TABLE
