WITH AGENT_TABLE AS (
    SELECT DE.OWNER
    , DE.OWNER_EMPLOYEE_ID
    , DE.CLOSED AS CLOSED_WON
    , DE.AVG_WIP_CYCLE AS CASE_AGE
    , DE.AVG_QA_SCORE AS QA
    FROM D_POST_INSTALL.V_CX_DEFAULT AS DE
)

SELECT *
FROM AGENT_TABLE
