WITH AGENT_TABLE AS (
    SELECT DF.FULL_NAME
         , DF.EMPLOYEE_ID
         , DF.EFFECTIVENESS
         , TO_CHAR(DF.EFFICIENCY, '999.0') AS EFFICIENCY
         , TO_CHAR(DF.QUALITY, '999.0') || '%' AS QUALITY
    FROM D_POST_INSTALL.V_CX_KPIS_DEFAULT_FORECLOSURE AS DF
)

SELECT *
FROM AGENT_TABLE
