WITH AGENT_TABLE AS (
    SELECT DD.FULL_NAME
         , DD.EMPLOYEE_ID
         , DD.EFFECTIVENESS
         , DD.EFFICIENCY
         , DD.QUALITY
    FROM D_POST_INSTALL.V_CX_KPIS_DEFAULT_DECEASED AS DD
)

SELECT *
FROM AGENT_TABLE
