WITH AGENT_TABLE AS (
    SELECT DF.FULL_NAME
         , DF.EMPLOYEE_ID
         , DF.EFFECTIVENESS
         , DF.EFFICIENCY
         , DF.QUALITY
    FROM D_POST_INSTALL.V_CX_KPIS_DEFAULT_FORECLOSURE AS DF
)

SELECT *
FROM AGENT_TABLE
