WITH AGENT_TABLE AS (
    SELECT ER.FULL_NAME
         , ER.EMPLOYEE_ID
         , ER.EFFECTIVENESS
         , TO_CHAR(ER.EFFICIENCY, '999.0') AS EFFICIENCY
         , TO_CHAR(ER.QUALITY, '999.0') || '%' AS QUALITY
    FROM D_POST_INSTALL.V_CX_KPIS_ER_T1 AS ER
)

SELECT *
FROM AGENT_TABLE